plugins {
    id "groovy"
    id "maven-publish"
    id "java-gradle-plugin"
    id 'jacoco'
    id 'idea'
    id 'eclipse'
    id 'com.gradle.plugin-publish' version '2.1.0'
}

group = 'com.yupzip'
version = '4.1.0'

compileJava {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    options.compilerArgs << '-parameters'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()

    testImplementation gradleTestKit()
    testImplementation platform('org.junit:junit-bom:6.1.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    runtimeOnly "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.21"
}

java {
    withSourcesJar()
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

gradlePlugin {
    website = 'https://github.com/yupzip/wsdl2java'
    vcsUrl = 'https://github.com/yupzip/wsdl2java'
    plugins {
        create('wsdl2java') {
            id = 'com.yupzip.wsdl2java'
            implementationClass = 'com.yupzip.wsdl2java.Wsdl2JavaPlugin'
            displayName = 'com.yupzip.wsdl2java'
            description = 'Generate java code form wsdl/xsd with cxf'
            tags.set(['wsdl2java'])
        }
    }
}

publishing {
    publications {
        create('mavenPublication', MavenPublication) {
            from components.java
        }
    }
}

wrapper {
    gradleVersion = '9.5.1'
}