package com.yupzip.wsdl2java

import org.junit.jupiter.api.Test

import static org.junit.jupiter.api.Assertions.assertEquals
import static org.junit.jupiter.api.Assertions.assertFalse
import static org.junit.jupiter.api.Assertions.assertTrue

class Wsdl2JavaTaskStabilizeTest {

    @Test
    void stripCommentDates_removesDateLineAfterGenerationMarker() {
        List<String> lines = [
                "/**",
                " * This class was generated by Apache CXF 4.1.2",
                " * 2024-01-15T10:30:45.123+01:00",
                " * Generated source version: 4.1.2",
                " */"
        ]

        Wsdl2JavaTask.stripCommentDates(lines)

        assertEquals([
                "/**",
                " * This class was generated by Apache CXF 4.1.2",
                " * Generated source version: 4.1.2",
                " */"
        ], lines)
    }

    @Test
    void stripCommentDates_matchesYearsBeyond2019() {
        // Regression: the original implementation matched only " * 201" literally,
        // so dates from 2020-01-01 onwards were never stripped.
        List<String> lines = [
                " * This class was generated by Apache CXF",
                " * 2024-06-03T12:00:00.000+10:00",
                " * Generated source version: 4.1.2"
        ]

        Wsdl2JavaTask.stripCommentDates(lines)

        assertEquals([
                " * This class was generated by Apache CXF",
                " * Generated source version: 4.1.2"
        ], lines)
    }

    @Test
    void stripCommentDates_leavesDatesWithoutGenerationMarkerAlone() {
        List<String> lines = [
                " * Some unrelated comment",
                " * 2024-01-15"
        ]
        List<String> original = new ArrayList<>(lines)

        Wsdl2JavaTask.stripCommentDates(lines)

        assertEquals(original, lines)
    }

    @Test
    void stabilizeXmlSeeAlso_sortsClassesAlphabetically() {
        List<String> lines = [
                "@XmlSeeAlso({Zebra.class, Apple.class, Mango.class})"
        ]

        Wsdl2JavaTask.stabilizeXmlSeeAlso(lines)

        assertEquals(["@XmlSeeAlso({Apple.class, Mango.class, Zebra.class})"], lines)
    }

    @Test
    void stabilizeXmlSeeAlso_ignoresLinesThatAreNotXmlSeeAlso() {
        List<String> lines = [
                "// not an annotation",
                "@SomethingElse({B.class, A.class})"
        ]
        List<String> original = new ArrayList<>(lines)

        Wsdl2JavaTask.stabilizeXmlSeeAlso(lines)

        assertEquals(original, lines)
    }

    @Test
    void stabilizeCommentLinks_sortsConsecutiveLinkLines() {
        List<String> lines = [
                " * Header",
                " * {@link Zebra }",
                " * {@link Apple }",
                " * {@link Mango }",
                " * Footer"
        ]

        Wsdl2JavaTask.stabilizeCommentLinks(lines)

        assertEquals([
                " * Header",
                " * {@link Apple }",
                " * {@link Mango }",
                " * {@link Zebra }",
                " * Footer"
        ], lines)
    }

    @Test
    void stabilizeXmlElementRef_sortsAndRepairsTrailingCommas() {
        List<String> lines = [
                "@XmlElementRefs({",
                "    @XmlElementRef(name = \"zebra\", type = JAXBElement.class),",
                "    @XmlElementRef(name = \"apple\", type = JAXBElement.class),",
                "    @XmlElementRef(name = \"mango\", type = JAXBElement.class)",
                "})"
        ]

        Wsdl2JavaTask.stabilizeXmlElementRef(lines)

        assertTrue(lines[1].contains("\"apple\""), "first ref should be 'apple', was: ${lines[1]}")
        assertTrue(lines[2].contains("\"mango\""), "second ref should be 'mango', was: ${lines[2]}")
        assertTrue(lines[3].contains("\"zebra\""), "third ref should be 'zebra', was: ${lines[3]}")
        assertTrue(lines[1].endsWith(","), "first ref must end with comma")
        assertTrue(lines[2].endsWith(","), "second ref must end with comma")
        assertFalse(lines[3].endsWith(","), "last ref must not end with comma")
    }

    @Test
    void runWithLocale_setsLocaleInsideAndRestoresAfter() {
        Locale originalDefault = Locale.getDefault()
        try {
            Locale.setDefault(Locale.ENGLISH)
            Locale[] captured = new Locale[1]

            Wsdl2JavaTask.runWithLocale(Locale.GERMAN, ({ -> captured[0] = Locale.getDefault() } as Closure<Void>))

            assertEquals(Locale.GERMAN, captured[0])
            assertEquals(Locale.ENGLISH, Locale.getDefault())
        } finally {
            Locale.setDefault(originalDefault)
        }
    }

    @Test
    void runWithLocale_restoresLocaleEvenWhenClosureThrows() {
        Locale originalDefault = Locale.getDefault()
        try {
            Locale.setDefault(Locale.ENGLISH)

            try {
                Wsdl2JavaTask.runWithLocale(Locale.GERMAN) { -> throw new RuntimeException("boom") }
            } catch (RuntimeException ignored) {
                // expected
            }

            assertEquals(Locale.ENGLISH, Locale.getDefault())
        } finally {
            Locale.setDefault(originalDefault)
        }
    }
}
